embed_assets: off

javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/underscore.js
    - public/javascripts/underscore.string.js
    - public/javascripts/utils.js
    - public/javascripts/backbone.js
    - public/javascripts/backbone_extensions.js
    - public/javascripts/bootstrap.js
    - public/javascripts/reader_utils.js
    - public/javascripts/application.js
    - public/javascripts/models/comments.js
    - public/javascripts/models/posts.js
    - public/javascripts/*/*.js
    - app/views/**/*.jst

stylesheets:
  common:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/bootstrap-responsive.css
    - public/stylesheets/custom.css
  commentview:
    - public/stylesheets/commentview.css
